services:
   redis: 
     image: redis:latest
     container_name: redis
     ports:
       - '6379:6379' 
   flask:
        build: .
        container_name: flask
        ports:
            - "5001:5001"
        volumes:
            - .:/code
        depends_on:
            - redis