"""empty message

Revision ID: 9417ee1e18b6
Revises: f1785eaa66c2
Create Date: 2024-12-04 20:37:39.552860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9417ee1e18b6'
down_revision = 'f1785eaa66c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TodoOwnerID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_todo_owner_id_user', 'user', ['TodoOwnerID'], ['UserID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_todo_owner_id_user', type_='foreignkey')
        batch_op.drop_column('TodoOwnerID')

    # ### end Alembic commands ###
