"""[feat] create status table

Revision ID: bf82e1cb4b23
Revises: 9417ee1e18b6
Create Date: 2024-12-04 21:11:10.180261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf82e1cb4b23'
down_revision = '9417ee1e18b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_status')
    with op.batch_alter_table('todo', schema=None) as batch_op:
        op.create_table('todo_status',
        sa.Column('StatusID', sa.INTEGER(), nullable=False),
        sa.Column('StatusDescription', sa.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint('StatusID'))

        batch_op.add_column(sa.Column('TodoStatusID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_status_todo_status_id', 'todostatus', ['TodoStatusID'], ['StatusID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_status_todo_status_id', type_='foreignkey')
        batch_op.drop_column('TodoStatusID')

    op.drop_table('todo_status')
    # ### end Alembic commands ###
