"""initial migrate

Revision ID: f1785eaa66c2
Revises: 
Create Date: 2024-09-27 10:41:03.782040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1785eaa66c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Todo',
    sa.Column('TodoID', sa.Integer(), nullable=False),
    sa.Column('TodoTitle', sa.String(length=50), nullable=True),
    sa.Column('TodoDescription', sa.String(length=200), nullable=True),
    sa.Column('TodoStartDate', sa.Datetime(), nullable=True),
    sa.Column('TodoEndDate', sa.Datetime(), nullable=True),
    sa.PrimaryKeyConstraint('TodoID')
    )



    op.create_table('User',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('UserLogin', sa.String(length=50), nullable=True),
    sa.Column('UserPassword', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('UserID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Todo')
    op.drop_table('User')

    # ### end Alembic commands ###
